version: '3.5'
services:

  in_memory_db:
    container_name: in_memory_db
    ports:
      - "6379:6379"
    image: redis:alpine


  auth_db:
    ports:
      - "5432:5432"
    image: postgres:alpine 
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=admin


      



